version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: note_verse_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: note_verse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: note_verse_qdrant
    ports:
      - "6333:6333"  
      - "6334:6334" 
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped

volumes:
  postgres-data:
  qdrant-data: